development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url: <%= ENV.fetch( redistogo-closed-20859 ) { "redis:redistogo-closed-20859" } %>
  # channel_prefix: myapp_production
